### ISSUE TITLE
Profile Photo Feature Broken

### ISSUE THREAD

**Issue by thoughtsociety** [openml/openml.org#66] opened 2019-05-03 20:29 UTC
Just joined and uploaded a photo (from Mac) which came out upside-down.
Edited that photo to flip it 180 so it would look right on my profile but there is no button to change the profile photo.

That should be standard.

I tried this in two browsers and the button is either missing or broken.

Also, why don't you recognize a photo from Mac and set it right-side-up?

Yes, this is tangential to openml.org main focus but hey, let's get this sorted.

Thanks

**Comment by janvanrijn** [comment] 2019-05-03 21:14
You are right, thanks for reporting this.

It seems that it used to work (actually, the button is there) but it is overlapped by update and cancel button.

**Comment by joaquinvanschoren** [comment] 2021-02-10 22:08
Duplicate of #125

**Closed as completed by joaquinvanschoren** 2021-02-10 22:08 UTC
